name: Unit Tests and Coverage
on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run Unit Tests with Coverage
        run: mvn --batch-mode test org.jacoco:jacoco-maven-plugin:prepare-agent verify

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/jacoco.xml

      - name: Extract Coverage Percentage
        run: |
          COVERAGE=$(xmllint --xpath "string(//report/counter[@type='LINE']/@covered)" target/site/jacoco/jacoco.xml)
          MISSED=$(xmllint --xpath "string(//report/counter[@type='LINE']/@missed)" target/site/jacoco/jacoco.xml)
          TOTAL=$((COVERAGE + MISSED))
          PERCENTAGE=$((COVERAGE * 100 / TOTAL))
          echo "Coverage: $PERCENTAGE%"
          echo "COVERAGE_PERCENTAGE=$PERCENTAGE" >> $GITHUB_ENV

      - name: Post Coverage Comment
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            📊 **Cobertura de código:** `${{ env.COVERAGE_PERCENTAGE }}%`
            ${{ env.COVERAGE_PERCENTAGE >= 80 && '✅ Cumple con el mínimo requerido.' || '❌ Insuficiente, se requiere al menos 80%.' }}
          GITHUB_TOKEN: ${{ secrets.GB_TOKEN }}

      - name: Fail if Coverage is Below 80%
        if: ${{ env.COVERAGE_PERCENTAGE < 80 }}
        run: exit 1
